### ISSUE TITLE
New structure spawning weirdly

### ISSUE THREAD

**Issue by Krampus69** [baguchan/HunterIllager#1]
Hello 👋 
The new structure is cool but it's not checking the ground under, which makes it create gigantic towers some times.
![2021-05-15_06 36 10](https://user-images.githubusercontent.com/81943963/118348082-20f2fc00-b548-11eb-8fc1-481fe53f8dc3.png)

**Comment by BugmanBugman** [comment]
![2021-05-16_01 09 59](https://user-images.githubusercontent.com/40730042/118841548-06918900-b88e-11eb-92a4-8d1aef770b59.png)
![2021-05-16_20 12 32](https://user-images.githubusercontent.com/40730042/118841552-08f3e300-b88e-11eb-8bd9-b76ea3ee2f98.png)
![2021-05-16_01 09 59](https://user-images.githubusercontent.com/40730042/118841559-0a251000-b88e-11eb-8702-4038df1c7c3d.png)
![2021-05-19_10 31 13](https://user-images.githubusercontent.com/40730042/118841569-0beed380-b88e-11eb-8a89-7db347750ef4.png)
Getting this too, they also spawn too close to villages

**Comment by baguchan** [comment]
fixed in 1.2.0!
so It mean no longer spawn in the village and no weird generation!
