### ISSUE TITLE
Structure Destruction

### ISSUE THREAD

**Issue by zachsai** [baguchan/HunterIllager#14]
![image](https://user-images.githubusercontent.com/63996164/149069747-9eae6f81-1970-4b5f-afa0-bbc3a3da6a39.png)
![image](https://user-images.githubusercontent.com/63996164/149069835-a5397270-5d4f-4302-a1fa-61bf605a1177.png)

Even with the spacing changes in the config, hunter illager structure still likes to overlap onto villages and destroy the structures.

**Comment by baguchi** [comment]
sorry for late. this bug is fixed on next version! ;)
