### ISSUE TITLE
[1.18.1] The Hunter House spawns in every biome

### ISSUE THREAD

**Issue by SilverDavidMC** [baguchan/HunterIllager#15]
Title says it all, the hunter house spawns in every biome. This is because `HunterHouseStructure.checkLocation` doesn't check to make sure it's in the proper biome.

Adding `context.validBiomeOnTop(Heightmap.Types.OCEAN_FLOOR_WG))` to the return statement should fix the issue.

Structure changes in 1.18 suck.

![2022-01-30_01 15 44](https://user-images.githubusercontent.com/15661705/151689070-54fa2483-be8b-419f-83ff-0fdcdb5557f6.png)

**Comment by DaddySpin** [comment]
I'll hop in with this amazing screenshot
![2022-02-01_08 37 38](https://user-images.githubusercontent.com/34575655/151989007-87cf1491-8ea9-4d54-b456-33c128501acb.png)

**Comment by baguchi** [comment]
oh I forgot about it 😞 
I'll fix on next version!
