### ISSUE TITLE
[1.18.2] No Spacing Config?

### ISSUE THREAD

**Issue by Gavin456b** [baguchan/HunterIllager#18]
As the title says I dont see a config for changing the spacing only the food & hunt whitelist

**Comment by baguchi** [comment]
sorry. Due to the change from 1.18.2 of vannila, it became a datapack format, so please adjust the datapack when you change the generation rate.
here is example:
https://github.com/baguchan/HunterIllager/blob/1.18/src/main/resources/data/hunterillager/worldgen/structure_set/hunter_house.json
