### ISSUE TITLE
Hunter-Illagers hold secondary items weirdly

### ISSUE THREAD

**Issue by BugmanBugman** [baguchan/HunterIllager#2]
![2021-05-08_16 01 10](https://user-images.githubusercontent.com/40730042/118375046-ce840080-b584-11eb-8807-b90cdd5a200d.png)
![2021-05-08_16 01 51](https://user-images.githubusercontent.com/40730042/118375047-cf1c9700-b584-11eb-860c-2b79058900ec.png)
![2021-05-08_16 01 52](https://user-images.githubusercontent.com/40730042/118375048-cfb52d80-b584-11eb-99f3-7558254e7dfb.png)
Usually illagers hide their secondary item when in fold place, like vindicators

**Comment by baguchan** [comment]
fixed in 1.2.0!
thanks for reporting!
