### ISSUE TITLE
Mod sites mislabeling

### ISSUE THREAD

**Issue by Ultimushadow** [baguchan/HunterIllager#23]
Hey there, I'm not sure if this is an issue with Modrinth/Curseforge and the way they set up their search system, but I noticed when searching for Fabric 1.20/1.20.1 mods, this one came up. The files show a Fabric version of this mod hasn't been updated in a while though, so obviously something there isn't quite right. Like I said, I'm not really sure if there's a way to fix that on your end, maybe you can just add a little list of what versions are supported by the different loaders on the description? Both sites make you click on a different page to go look at the files, and I assume most people wouldn't think to get after using a query for specifically Fabric. I do hope that eventually this mod will be available for Fabric, seems pretty cool!

(I also noticed this mislabel with "Enchant With Mob" and I _definitely_ look forward to that getting ported if that's a possibility)

**Comment by baguchi** [comment]
yeah... I tried fabric once... but I'm tired of dealing with both fabric and forge
I know peaple want fabric one
Even if I delete the fabric version to make it only forge, it will take time, and I think that deleting and recreating the mod for fabric tag just for that will confuse the player.
please let's me know

**Comment by Ultimushadow** [comment]
Yeah that's fair, don't worry about it, though you'll probably get more people asking for Fabric as long as the mod is still listed under fabric. I think it might be worth reuploading the Fabric version as a separate project without the label if you aren't planning on continuing - otherwise, it's going to show up as Fabric for every version you port to!
