### ISSUE TITLE
1.20.1 Failed to create model for hunters_return:hunter

### ISSUE THREAD

**Issue by PercyJames** [baguchan/HunterIllager#36]
[crash-2024-04-11_14.16.40-client.txt](https://github.com/baguchan/HuntersReturn/files/14949918/crash-2024-04-11_14.16.40-client.txt)

**Comment by PercyJames** [comment]
also I think this mod caused a resource loading fail. I couldn't load my packs until i removed the mod.

**Comment by baguchi** [comment]
fixed in newer version
