### ISSUE TITLE
[1.21-Neo] Random server crash related to "ProjectileWeaponItem.customArrow" / "performRangedAttack" / "aiStep"

### ISSUE THREAD

**Issue by Gbergz** [baguchan/HunterIllager#38]
### Versions:
**MC:** 1.21
**NeoForge:** 21.0.30
**Hunters Return:** 17.0.1

### Crash Report: 
https://gist.githubusercontent.com/Gbergz/b1de60934a3363a7611c0a932aaab8d7/raw/b1d14224ca5d1e2bc0668028ab5c3578e3ca729f/gistfile1.txt

**Comment by baguchi** [comment]
fixed in next version!
