### ISSUE TITLE
Found reference to unknown structure

### ISSUE THREAD

**Issue by ghost** [baguchan/HunterIllager#6]
[16:05:59] [Server thread/WARN]: Found reference to unknown structure 'hunterillager:hunter_house' in chunk [39, 43], discarding
My server Keeps giving me this warning. I am running a server with the Better Minecraft mod pack from CurseForge.
The chunk location keeps changing as the warning pops up.
[latest.log](https://github.com/Evoslab/HunterIllager/files/7041857/latest.log)

**Comment by baguchi** [comment]
It fixed on 1.17.1-2.4.0 you shoud try out it
